"""initial_schema

Revision ID: 211eac0ec478
Revises: 
Create Date: 2026-07-10 12:13:29.222830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211eac0ec478'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('counterparty', sa.String(length=300), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('responsible', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sections', sa.Text(), nullable=True),
    sa.Column('section_steps', sa.Text(), nullable=True),
    sa.Column('contract_type', sa.String(length=20), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('received_date', sa.DateTime(), nullable=True),
    sa.Column('processing_date', sa.DateTime(), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('revision_date', sa.DateTime(), nullable=True),
    sa.Column('signing_date', sa.DateTime(), nullable=True),
    sa.Column('sent_date', sa.DateTime(), nullable=True),
    sa.Column('archive_date', sa.DateTime(), nullable=True),
    sa.Column('destroyed_date', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('document_date', sa.String(length=20), nullable=True),
    sa.Column('additional_number', sa.String(length=100), nullable=True),
    sa.Column('additional_date', sa.String(length=20), nullable=True),
    sa.Column('service_section', sa.String(length=200), nullable=True),
    sa.Column('service_subtype', sa.String(length=200), nullable=True),
    sa.Column('brief_subject', sa.String(length=500), nullable=True),
    sa.Column('place_conclusion', sa.String(length=200), nullable=True),
    sa.Column('place_service', sa.String(length=200), nullable=True),
    sa.Column('initiator', sa.String(length=300), nullable=True),
    sa.Column('government_id', sa.String(length=100), nullable=True),
    sa.Column('payment_form', sa.String(length=200), nullable=True),
    sa.Column('original_status', sa.String(length=200), nullable=True),
    sa.Column('outgoing_info', sa.Text(), nullable=True),
    sa.Column('signatory', sa.String(length=300), nullable=True),
    sa.Column('signatory_doc', sa.String(length=300), nullable=True),
    sa.Column('counterparty_details', sa.Text(), nullable=True),
    sa.Column('electronic_copy', sa.String(length=100), nullable=True),
    sa.Column('prolongation', sa.String(length=200), nullable=True),
    sa.Column('prolongation_days', sa.Integer(), nullable=True),
    sa.Column('renewal_required', sa.Boolean(), nullable=True),
    sa.Column('planned_start', sa.String(length=20), nullable=True),
    sa.Column('planned_end', sa.String(length=20), nullable=True),
    sa.Column('actual_start', sa.String(length=20), nullable=True),
    sa.Column('actual_end', sa.String(length=20), nullable=True),
    sa.Column('validity_period', sa.String(length=200), nullable=True),
    sa.Column('monthly_amount', sa.Float(), nullable=True),
    sa.Column('amount_no_tax', sa.Float(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('amount_with_tax', sa.Float(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('amount_remaining', sa.Float(), nullable=True),
    sa.Column('date_sent_to_sign', sa.String(length=20), nullable=True),
    sa.Column('date_received_signed', sa.String(length=20), nullable=True),
    sa.Column('termination_date', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('tag', sa.String(length=100), nullable=True),
    sa.Column('tag_color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=True),
    sa.Column('short_name', sa.String(length=200), nullable=True),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('kpp', sa.String(length=20), nullable=True),
    sa.Column('ogrn', sa.String(length=30), nullable=True),
    sa.Column('legal_address', sa.String(length=500), nullable=True),
    sa.Column('actual_address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('bank_name', sa.String(length=300), nullable=True),
    sa.Column('bik', sa.String(length=20), nullable=True),
    sa.Column('corr_account', sa.String(length=30), nullable=True),
    sa.Column('current_account', sa.String(length=30), nullable=True),
    sa.Column('director', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_card')
    op.drop_table('news')
    op.drop_table('contracts')
    # ### end Alembic commands ###
